### PR TITLE
Allow text-2

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Hello, I am once again asking for a version bound update :-)

**Comment by klangner** [comment]
Hi, do you need new deployment also?

**Comment by TristanCacqueray** [comment]
A new release could be useful yes, so that ghc-9.4 can use the library from hackage.

**Comment by klangner** [comment]
Ok, there is a new 0.3.2 version uploaded

**Comment by TristanCacqueray** [comment]
@klangner Thanks!

**Pull request merged**
